# Generated by Django 5.2.8 on 2025-11-23 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', '-end_date']},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-date_earned']},
        ),
        migrations.AddField(
            model_name='reward',
            name='date_earned',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(upload_to='cv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.skillcategory'),
        ),
    ]
